config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'
  root 'chat#index'
  #mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :chat
  resources :register
  resources :users
  resources :sessions
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  #post 'show' => 'chat#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :message, dependent: :destroy
    validates :username, presence: true, uniqueness: true,
        length: { minimum: 2 }
    validates :password, presence: true, length: { minimum: 6 }
    def authenticate(user, password)
        username = user.username
        if username && user.password == password
            user
        else
            nil
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #protect_from_forgery with: :exception # default enabled
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
    include SessionsHelper
    def index
        @users = User.all
        @messages = Message.all
        @message = Message.new
    end
    def show
        @user = User.find(params[:id])
        @messages = Message.all
        @message = Message.new
    end
    def new
        @message = Message.new
    end
    def edit
    end
    def update
    end
    def create
        @message = Message.create(msg_params)
        @message.user_id = current_user.id
        @username = User.find(current_user.id).username
        if @message.save
            puts "message save"
            ActionCable.server.broadcast "chat_channel",
                content: [@message, @username]
                #content: @message.body 
        else
            puts "message save failed"
        end
    end
    def destroy
    end
    private
    def msg_params
        params.require(:message).permit(:body)
    end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
    include SessionsHelper
    def index
        @user = User.new
    end
    def show
        @user = User.find(params[:id])
    end
    def new
        @user = User.new
    end
    def edit
    end
    def update
    end
    def create
        @user = User.create(user_params)
        if @user.save
            log_in @user
            flash[:success] = "Welcome to chat room my friend!"
            redirect_to @user
        else
            render "new"
        end
    end
    def destroy
    end
    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include SessionsHelper
    def new
    end
    def create
        user = User.find_by(username: params["sessions"]["username"])
        if user && user.authenticate(user, params["sessions"]["password"])
            log_in user
            redirect_to user
        else 
            flash[:alert] = 'Invalid username/password!'
            render 'new'
        end
    end
    def destroy
        log_out
        render 'new'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    def show
        @user = User.find(params[:id])
        @user_id = params[:id].to_i # url string to integer
    end
    def new
        @user = User.new
    end
    def edit
    end
    def update
    end
    def create
    end
    def destroy
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
    def logged_in?
        !current_user.nil?
    end
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    def current_user
        @current_user || User.find_by(id: session[:user_id])
    end
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
    def logged_in?
        !current_user.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/index.html.erb
<head>
	<script src="http://cdn.bootcss.com/jquery/1.9.1/jquery.js"></script>
</head>
<h1>Chat room index page</h1>

<h2><%= link_to "users home page", "/users" %></h2>

<p>below is what we discuss</p>
<div id="msgbox" style="
    height: 600px;
    margin: 0;
    padding: 10px 0 1px;
">
<div id="messages" style="
    height: 100%;
    overflow-y: scroll;
">
	<% @messages.each do |msg| %>
		<div id="msg">
			<p><%= @users.find(msg.user_id).username %>:  <%= msg.body %>
		</div>
	<% end %>
</div>
</div>

<div id="chatInput" style="margin-bottom: 30px;position: fixed;bottom: 0;left: 0;height: 150px;width: 100%;background: #f6f6f6;/* color: #a1a1a1; */padding: 10px;">
<% if logged_in? %>
    <p>I am <%= current_user.username %></p>
    <%= form_for(@message, url: "/chat", remote: true) do |form| %>
      <div class="field">
        <%= form.label :畅所欲言! %><br>
        <%= form.text_area :body %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
    <br>
    <%= link_to 'log out', "/logout", method: "delete" %>
<% else %>
    <%= link_to 'Sign up', register_path(:new) %>
    <p>Already has an account? <%= link_to "Log in", "/login" %></p>
<% end %>
</div>

app/views/chat/show.html.erb
<head>
    <script src="http://cdn.bootcss.com/jquery/1.9.1/jquery.js"></script>
</head>
<h1>Chat room show page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/register/create.html.erb
<h1>i am register create page</h1>

app/views/register/index.html.erb
<%= link_to 'Home Page', "/" %>
<h1>I am register index page</h1>
<%= link_to 'sign up', register_path(:new) %>

app/views/register/new.html.erb
<h1>i am register new page</h1>

<%= form_for :user, url: "/register" do |f| %>

    <% if @user.errors.any? %>
    <div id="error_explanation">
        <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
        </h2>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>
    <p>
    <%= f.label :name %><br>
    <%= f.text_field :username %>
    </p>

    <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
    </p>

    <p>
    <%= f.submit "Create my account", class: "btn btn-primary" %>
    </p>

<% end %>
<%= link_to 'Log in', "/login" %>

app/views/register/show.html.erb
<h1>I am register show page</h1>

app/views/users/index.html.erb
<h1>I am user index page</h1>
    <table>
        <% if current_user %>
        <tr>
        <th>我是 <%= current_user.username %></th>
        </tr>
        <% end %>
        
    <% @users.each do |u| %>
    <tr>
      <td><%= u.username %> </td>
      <td><%= link_to 'Show', user_path(u) %></td>
      <td><%= (!current_user.nil? and current_user.id == u.id) ? ' 当前登录用户':'' %> </td>
    </tr>
    <% end %>
    </table>
<%= link_to "Sign up", register_path(:new) %>

app/views/users/new.html.erb
<%= link_to 'home page', "/" %>

app/views/users/show.html.erb
<%= link_to "users home page", "/users" %>
<% if flash[:success] %>
    <div class="notice"><%= flash[:success] %></div>
<% end %>
<p>Hi everyone</p>
<p>My name is <%= @user.username %></p>
<% if (!current_user.nil?) and (current_user.id == @user_id) %>
    <%= link_to 'Join the chat!', "/" %><br>
    <%= link_to 'log out', "/logout", method: "delete" %>
<% else %>
    <%= link_to 'Login to join the chat!', "/login" %>
<% end %>